### ISSUE TITLE
API not logging in

### ISSUE THREAD

**Issue by ProjectColdheart** [ddxtanx/skyward_api#1]
When I try to login, all I get is:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\skyward_api\api.py", line 193, in login
    data = parse_login_text(self.base_url, text)
  File "C:\ProgramData\Anaconda3\lib\site-packages\skyward_api\helpers.py", line 33, in parse_login_text
    return data
  File "C:\ProgramData\Anaconda3\lib\site-packages\skyward_api\helpers.py", line 14, in parse_login_text

IndexError: list index out of range

**Comment by ddxtanx** [comment]
From what I have seen, the login mechanism that I used when writing the code has now been modified by Skyward, so that a new way of keeping cookies needs to be found. That, from what I can gather, is causing these weird errors of lists being empty and cookies being invalid.
